version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    groups:
      all-dependencies:
        patterns:
          - "*"
    schedule:
      interval: weekly
      time: "08:00"
      timezone: Australia/Melbourne
  - package-ecosystem: npm
    directory: "/"
    groups:
      all-dependencies:
        patterns:
          - "*"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Australia/Melbourne
    open-pull-requests-limit: 1
    # Always increase the version requirement
    # to match the new version.
    versioning-strategy: increase
